FROM golang:1.21-bullseye

RUN apt-get update && apt-get install -y \
    libayatana-appindicator3-dev \
    libgtk-3-dev \
    tar \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN git config --global --add safe.directory /app
CMD ["make", "release"]
